from __future__ import annotations


DATABASE = "short_video_ops"


TABLE_META = {
    "users": ("平台用户主表", "用户增长"),
    "user_profiles": ("用户画像信息", "用户增长"),
    "user_devices": ("用户常用设备", "用户增长"),
    "acquisition_channels": ("用户获客渠道", "渠道投放"),
    "user_registrations": ("用户注册记录", "用户增长"),
    "user_activations": ("新用户激活结果", "用户增长"),
    "user_daily_activity": ("用户每日活跃汇总", "用户增长"),
    "user_retention": ("用户留存里程碑", "用户增长"),
    "user_tags": ("用户标签定义", "用户增长"),
    "user_tag_relations": ("用户标签关系", "用户增长"),
    "user_sessions": ("用户访问会话", "用户增长"),
    "user_lifecycle_snapshots": ("用户生命周期快照", "用户增长"),
    "user_churn_events": ("用户流失识别记录", "用户增长"),
    "recall_campaigns": ("用户召回活动", "用户增长"),
    "recall_touches": ("召回触达记录", "用户增长"),
    "recall_results": ("召回效果记录", "用户增长"),
    "growth_daily_metrics": ("增长运营日指标", "用户增长"),
    "growth_targets": ("增长运营月度目标", "用户增长"),
    "ad_accounts": ("广告投放账户", "渠道投放"),
    "ad_campaigns": ("广告投放计划", "渠道投放"),
    "ad_creatives": ("广告创意素材", "渠道投放"),
    "ad_daily_stats": ("广告计划每日效果", "渠道投放"),
    "channel_attributions": ("用户渠道归因结果", "渠道投放"),
    "channel_conversion_events": ("渠道转化事件", "渠道投放"),
    "channel_targets": ("渠道月度投放目标", "渠道投放"),
    "budget_adjustments": ("投放预算调整记录", "渠道投放"),
    "creators": ("内容创作者主表", "内容运营"),
    "creator_profiles": ("创作者画像", "内容运营"),
    "content_categories": ("内容分类", "内容运营"),
    "contents": ("短视频内容主表", "内容运营"),
    "content_tags": ("内容标签定义", "内容运营"),
    "content_tag_relations": ("内容标签关系", "内容运营"),
    "video_exposures": ("视频曝光明细", "内容运营"),
    "video_plays": ("视频播放明细", "内容运营"),
    "video_interactions": ("视频互动明细", "内容运营"),
    "content_daily_metrics": ("内容日运营指标", "内容运营"),
    "creator_daily_metrics": ("创作者日运营指标", "内容运营"),
    "content_audits": ("内容审核记录", "内容运营"),
    "content_reports": ("用户内容举报记录", "内容运营"),
    "trending_topics": ("平台热点话题", "内容运营"),
    "topic_content_relations": ("热点话题内容关系", "内容运营"),
}


PRIMARY_KEYS = {
    "users": ["user_id"],
    "user_profiles": ["user_id"],
    "user_devices": ["device_id"],
    "acquisition_channels": ["channel_id"],
    "user_registrations": ["registration_id"],
    "user_activations": ["activation_id"],
    "user_daily_activity": ["activity_id"],
    "user_retention": ["retention_id"],
    "user_tags": ["tag_id"],
    "user_tag_relations": ["relation_id"],
    "user_sessions": ["session_id"],
    "user_lifecycle_snapshots": ["snapshot_id"],
    "user_churn_events": ["churn_event_id"],
    "recall_campaigns": ["recall_campaign_id"],
    "recall_touches": ["touch_id"],
    "recall_results": ["recall_result_id"],
    "growth_daily_metrics": ["metric_id"],
    "growth_targets": ["target_id"],
    "ad_accounts": ["ad_account_id"],
    "ad_campaigns": ["ad_campaign_id"],
    "ad_creatives": ["creative_id"],
    "ad_daily_stats": ["ad_stat_id"],
    "channel_attributions": ["attribution_id"],
    "channel_conversion_events": ["conversion_event_id"],
    "channel_targets": ["channel_target_id"],
    "budget_adjustments": ["adjustment_id"],
    "creators": ["creator_id"],
    "creator_profiles": ["creator_id"],
    "content_categories": ["category_id"],
    "contents": ["content_id"],
    "content_tags": ["content_tag_id"],
    "content_tag_relations": ["content_tag_relation_id"],
    "video_exposures": ["exposure_id"],
    "video_plays": ["play_id"],
    "video_interactions": ["interaction_id"],
    "content_daily_metrics": ["content_metric_id"],
    "creator_daily_metrics": ["creator_metric_id"],
    "content_audits": ["audit_id"],
    "content_reports": ["report_id"],
    "trending_topics": ["topic_id"],
    "topic_content_relations": ["topic_content_id"],
}


ROLE_TABLES = {
    "growth_ops": [
        "users", "user_profiles", "user_devices", "acquisition_channels",
        "user_registrations", "user_activations", "user_daily_activity",
        "user_retention", "user_tags", "user_tag_relations", "user_sessions",
        "user_lifecycle_snapshots", "user_churn_events", "recall_campaigns",
        "recall_touches", "recall_results", "growth_daily_metrics", "growth_targets",
    ],
    "channel_ops": [
        "users", "user_profiles", "user_devices", "acquisition_channels",
        "user_registrations", "user_activations", "user_daily_activity",
        "user_retention", "ad_accounts", "ad_campaigns", "ad_creatives",
        "ad_daily_stats", "channel_attributions", "channel_conversion_events",
        "channel_targets", "budget_adjustments",
    ],
    "content_ops": [
        "users", "user_profiles", "user_tags", "user_tag_relations", "creators",
        "creator_profiles", "content_categories", "contents", "content_tags",
        "content_tag_relations", "video_exposures", "video_plays",
        "video_interactions", "content_daily_metrics", "creator_daily_metrics",
        "content_audits", "content_reports", "trending_topics",
        "topic_content_relations",
    ],
}


RELATIONS = [
    ("acquisition_channels", "channel_id", "users", "register_channel_id", "用户通过渠道注册"),
    ("users", "user_id", "user_profiles", "user_id", "用户对应画像"),
    ("users", "user_id", "user_devices", "user_id", "用户绑定设备"),
    ("users", "user_id", "user_registrations", "user_id", "用户产生注册记录"),
    ("acquisition_channels", "channel_id", "user_registrations", "channel_id", "注册归因到渠道"),
    ("user_registrations", "registration_id", "user_activations", "registration_id", "注册产生激活结果"),
    ("users", "user_id", "user_activations", "user_id", "用户对应激活结果"),
    ("users", "user_id", "user_daily_activity", "user_id", "用户产生活跃记录"),
    ("users", "user_id", "user_retention", "user_id", "用户对应留存结果"),
    ("acquisition_channels", "channel_id", "user_retention", "channel_id", "留存结果归因到渠道"),
    ("user_tags", "tag_id", "user_tag_relations", "tag_id", "标签分配给用户"),
    ("users", "user_id", "user_tag_relations", "user_id", "用户获得标签"),
    ("users", "user_id", "user_sessions", "user_id", "用户产生访问会话"),
    ("user_devices", "device_id", "user_sessions", "device_id", "会话使用设备"),
    ("acquisition_channels", "channel_id", "user_sessions", "channel_id", "会话来源渠道"),
    ("users", "user_id", "user_lifecycle_snapshots", "user_id", "用户对应生命周期快照"),
    ("users", "user_id", "user_churn_events", "user_id", "用户产生流失事件"),
    ("recall_campaigns", "recall_campaign_id", "recall_touches", "recall_campaign_id", "召回活动产生触达"),
    ("users", "user_id", "recall_touches", "user_id", "用户收到召回触达"),
    ("recall_touches", "touch_id", "recall_results", "touch_id", "触达产生召回结果"),
    ("acquisition_channels", "channel_id", "growth_daily_metrics", "channel_id", "增长指标按渠道统计"),
    ("acquisition_channels", "channel_id", "growth_targets", "channel_id", "增长目标按渠道制定"),
    ("acquisition_channels", "channel_id", "ad_accounts", "channel_id", "广告账户归属渠道"),
    ("ad_accounts", "ad_account_id", "ad_campaigns", "ad_account_id", "广告账户包含计划"),
    ("acquisition_channels", "channel_id", "ad_campaigns", "channel_id", "广告计划投放至渠道"),
    ("ad_campaigns", "ad_campaign_id", "ad_creatives", "ad_campaign_id", "广告计划使用创意素材"),
    ("ad_campaigns", "ad_campaign_id", "ad_daily_stats", "ad_campaign_id", "广告计划产生每日效果"),
    ("users", "user_id", "channel_attributions", "user_id", "用户对应渠道归因"),
    ("acquisition_channels", "channel_id", "channel_attributions", "channel_id", "归因结果对应渠道"),
    ("users", "user_id", "channel_conversion_events", "user_id", "用户产生渠道转化事件"),
    ("acquisition_channels", "channel_id", "channel_conversion_events", "channel_id", "转化事件归因到渠道"),
    ("acquisition_channels", "channel_id", "channel_targets", "channel_id", "渠道对应月度目标"),
    ("ad_campaigns", "ad_campaign_id", "budget_adjustments", "ad_campaign_id", "广告计划产生预算调整"),
    ("creators", "creator_id", "creator_profiles", "creator_id", "创作者对应画像"),
    ("creators", "creator_id", "contents", "creator_id", "创作者发布内容"),
    ("content_categories", "category_id", "contents", "category_id", "内容归属分类"),
    ("contents", "content_id", "content_tag_relations", "content_id", "内容获得标签"),
    ("content_tags", "content_tag_id", "content_tag_relations", "content_tag_id", "标签关联内容"),
    ("users", "user_id", "video_exposures", "user_id", "用户获得视频曝光"),
    ("contents", "content_id", "video_exposures", "content_id", "内容获得曝光"),
    ("video_exposures", "exposure_id", "video_plays", "exposure_id", "曝光产生播放"),
    ("users", "user_id", "video_plays", "user_id", "用户产生播放"),
    ("contents", "content_id", "video_plays", "content_id", "内容产生播放"),
    ("video_plays", "play_id", "video_interactions", "play_id", "播放产生互动"),
    ("users", "user_id", "video_interactions", "user_id", "用户产生互动"),
    ("contents", "content_id", "video_interactions", "content_id", "内容获得互动"),
    ("contents", "content_id", "content_daily_metrics", "content_id", "内容对应日指标"),
    ("creators", "creator_id", "creator_daily_metrics", "creator_id", "创作者对应日指标"),
    ("contents", "content_id", "content_audits", "content_id", "内容产生审核记录"),
    ("users", "user_id", "content_reports", "user_id", "用户提交内容举报"),
    ("contents", "content_id", "content_reports", "content_id", "举报指向内容"),
    ("trending_topics", "topic_id", "topic_content_relations", "topic_id", "热点话题关联内容"),
    ("contents", "content_id", "topic_content_relations", "content_id", "内容参与热点话题"),
]


FIELD_LABELS = {
    "user_id": "用户编号", "creator_id": "创作者编号", "content_id": "内容编号",
    "channel_id": "渠道编号", "registration_id": "注册记录编号",
    "activation_id": "激活记录编号", "activity_id": "活跃记录编号",
    "retention_id": "留存记录编号", "session_id": "会话编号",
    "registered_at": "注册时间", "registration_date": "注册日期",
    "activity_date": "活跃日期", "retention_day": "留存天数",
    "is_retained": "是否留存", "is_activated": "是否激活",
    "activation_seconds": "激活耗时", "channel_name": "渠道名称",
    "channel_type": "渠道类型", "nickname": "用户昵称", "gender": "性别",
    "age_group": "年龄段", "region": "地区", "province": "省份", "city": "城市",
    "device_type": "设备类型", "platform": "平台", "app_version": "应用版本",
    "active_minutes": "活跃时长", "session_count": "会话次数",
    "play_count": "播放次数", "interaction_count": "互动次数",
    "lifecycle_stage": "生命周期阶段", "churn_level": "流失等级",
    "campaign_name": "活动名称", "touch_channel": "触达方式",
    "recalled": "是否召回", "new_users": "新增用户数",
    "activated_users": "激活用户数", "day1_retained_users": "次日留存用户数",
    "day7_retained_users": "七日留存用户数", "target_month": "目标月份",
    "ad_campaign_id": "广告计划编号", "ad_campaign_name": "广告计划名称",
    "creative_id": "创意编号", "creative_type": "创意类型",
    "impressions": "曝光次数", "clicks": "点击次数", "conversions": "转化次数",
    "spend": "广告消耗", "attribution_type": "归因方式", "conversion_type": "转化类型",
    "creator_name": "创作者名称", "creator_level": "创作者等级",
    "category_id": "内容分类编号", "category_name": "内容分类名称",
    "content_title": "内容标题", "content_status": "内容状态",
    "published_at": "发布时间", "duration_seconds": "视频时长",
    "exposure_id": "曝光编号", "exposed_at": "曝光时间", "position_name": "推荐位置",
    "play_id": "播放编号", "played_at": "播放时间", "watch_seconds": "观看时长",
    "completion_rate": "完播率", "interaction_type": "互动类型",
    "content_metric_id": "内容指标编号", "creator_metric_id": "创作者指标编号",
    "audit_status": "审核状态", "report_reason": "举报原因", "topic_name": "话题名称",
}


FIELD_ALIASES = {
    "new_users": ["新增", "新增用户", "拉新人数"],
    "is_activated": ["激活", "有效激活"],
    "is_retained": ["留存", "留存用户"],
    "retention_day": ["次留", "七留", "留存周期"],
    "spend": ["消耗", "投放费用", "广告花费"],
    "impressions": ["曝光", "展示量"],
    "clicks": ["点击", "点击量"],
    "conversions": ["转化", "转化量"],
    "watch_seconds": ["观看时长", "播放时长"],
    "completion_rate": ["完播率", "播放完成率"],
    "interaction_type": ["点赞评论分享", "互动行为"],
}


# 派生指标依赖用于增强字段检索，不改变字段本身的业务含义。
FIELD_RETRIEVAL_CONTEXT = {
    "clicks": ["转化率分母", "转化率由转化次数除以点击次数计算"],
    "conversions": [
        "转化率分子",
        "CPA分母",
        "实际CPA由广告消耗除以转化次数计算",
    ],
    "spend": ["CPA分子", "实际CPA", "实际CPA由广告消耗除以转化次数计算"],
}
